// Test that main.json (Tauri 2 runtime ACL) includes every `allow-*`
// permission listed in default.toml.
//
// Why this matters (Lesson 219, 2026-08-22):
// In Tauri 2, the permissions array in `default.toml` declares which
// allow-* identifiers EXIST (autogenerated from app_commands.toml).
// But the actual runtime ACL for each window is `capabilities/*.json`.
// Adding to default.toml alone is NOT enough — Tauri silently rejects
// any unlisted command with "Command X not allowed by ACL" at runtime.
//
// This test would have caught the rc36 regression where mc_terminal_*
// (and rc35 Settings commands) were added to default.toml/app_commands.toml
// but never to main.json. JS invocations failed with the cryptic ACL
// error and the user saw a "broken Terminal" with no other symptoms.

use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;

/// Crude default.toml parser: scan for `"allow-*"` quoted strings. Our
/// default.toml uses simple `"allow-foo-bar"` literals — no fancy TOML
/// features (no multi-line strings, no escape sequences). A regex is
/// sufficient and avoids pulling in the `toml` crate as a dep.
fn quoted_allow_strings(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(idx) = rest.find("\"allow-") {
        rest = &rest[idx + 1..]; // skip the opening quote
        if let Some(end) = rest.find('"') {
            out.push(rest[..end].to_string());
            rest = &rest[end + 1..];
        } else {
            break;
        }
    }
    out
}

fn permissions_in_default_toml(root: &PathBuf) -> Vec<String> {
    let path = root.join("src-tauri/permissions/default.toml");
    let s = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    quoted_allow_strings(&s)
}

fn permissions_in_main_json(root: &PathBuf) -> Vec<String> {
    let path = root.join("src-tauri/capabilities/main.json");
    let s = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    let v: serde_json::Value = serde_json::from_str(&s)
        .unwrap_or_else(|e| panic!("main.json must be valid JSON: {}", e));

    let arr = v
        .get("permissions")
        .and_then(|p| p.as_array())
        .expect("main.json permissions must be an array");

    arr.iter()
        .filter_map(|x| x.as_str().map(String::from))
        .filter(|s| s.starts_with("allow-"))
        .collect()
}

fn project_root() -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir.parent().unwrap().to_path_buf()
}

#[test]
fn test_main_json_includes_every_default_toml_allow() {
    let root = project_root();
    let in_toml = permissions_in_default_toml(&root);
    let in_json = permissions_in_main_json(&root);

    let json_set: HashSet<&String> = in_json.iter().collect();

    let mut missing = Vec::new();
    for p in &in_toml {
        if !json_set.contains(p) {
            missing.push(p.clone());
        }
    }

    assert!(
        missing.is_empty(),
        "\n\n❌ Tauri ACL drift detected!\n\
         These permissions are declared in default.toml but missing from \
         src-tauri/capabilities/main.json:\n  - {}\n\n\
         Fix: add the missing identifiers to main.json's `permissions` \
         array. The runtime ACL is read from main.json, NOT from \
         default.toml. Adding to default.toml alone means JS will see \
         'Command X not allowed by ACL'.\n\
         (Lesson 219, 2026-08-22 — caught the rc35/rc36 regression.)\n",
        missing.join("\n  - ")
    );

    println!("\ndefault.toml: {} allow-* permissions", in_toml.len());
    println!("main.json:    {} allow-* permissions", in_json.len());
    println!("✓ All default.toml allow-* permissions are wired into main.json\n");
}

#[test]
fn test_default_toml_has_at_least_one_allow() {
    let root = project_root();
    let in_toml = permissions_in_default_toml(&root);
    assert!(
        !in_toml.is_empty(),
        "default.toml has no allow-* permissions — likely a parse error"
    );
}
